package com.v1byte.corelink;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.util.Base64;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.view.WindowInsets;
import android.view.animation.AlphaAnimation;
import android.view.animation.Animation;
import android.view.animation.TranslateAnimation;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private final int BG=Color.rgb(7,10,18), CARD=Color.rgb(13,23,36), BORDER=Color.rgb(29,69,93), TEXT=Color.rgb(225,239,250), MUTED=Color.rgb(126,153,173), BLUE=Color.rgb(0,158,221), GREEN=Color.rgb(72,218,150), RED=Color.rgb(245,110,110), AMBER=Color.rgb(238,190,81);
    private final ExecutorService executor=Executors.newSingleThreadExecutor();
    private EditText endpoint,prompt; private Spinner modelSpinner; private TextView bridgeStatus,chat,attachmentLabel; private Button connect,send,attach; private LinearLayout connectorDrawer; private String bridge="http://127.0.0.1:8787"; private String attachmentName="",attachmentMime="",attachmentBase64=""; private static final int PICK_FILE=401;
    private final String commands="pkg update -y\npkg install -y nodejs git curl\ngit clone https://github.com/v1-byte/CORELINK.git\ncd CORELINK/bridge\ncp config.template .env\nbash start-termux.sh";
    @Override public void onCreate(Bundle state){super.onCreate(state); Window w=getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(BG);w.getDecorView().setSystemUiVisibility(0);build();}
    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private TextView text(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans",Typeface.NORMAL));return v;}
    private GradientDrawable bg(int c,int st){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(12));if(st!=0)d.setStroke(dp(1),st);return d;}
    private void pad(View v,int h,int y){v.setPadding(dp(h),dp(y),dp(h),dp(y));}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w<0?w:dp(w),h<0?h:dp(h));}
    private void heading(LinearLayout r,String s){TextView t=text(s,10,BLUE);t.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);t.setPadding(0,dp(14),0,dp(7));r.addView(t);}
    private Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);b.setAllCaps(false);b.setMinHeight(0);b.setMinWidth(0);b.setPadding(dp(3),0,dp(3),0);b.setBackground(bg(c,0));b.setOnTouchListener((v,e)->{if(e.getAction()==1){v.animate().scaleX(1f).scaleY(1f).setDuration(100).start();}else if(e.getAction()==0){v.animate().scaleX(.96f).scaleY(.96f).setDuration(80).start();}return false;});return b;}
    private void animateIn(View v){v.setAlpha(0f);v.setTranslationY(dp(10));v.animate().alpha(1f).translationY(0).setDuration(280).start();}
    private void build(){
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);pad(root,16,10);scroll.addView(root);
        root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(16),i.getInsets(WindowInsets.Type.statusBars()).top+dp(8),dp(16),i.getInsets(WindowInsets.Type.navigationBars()).bottom+dp(10));return i;});
        LinearLayout header=row();header.setPadding(0,0,0,dp(12));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.ai_connector_icon);logo.setScaleType(ImageView.ScaleType.CENTER_CROP);header.addView(logo,lp(42,42));AlphaAnimation brainPulse=new AlphaAnimation(.55f,1f);brainPulse.setDuration(900);brainPulse.setRepeatMode(Animation.REVERSE);brainPulse.setRepeatCount(Animation.INFINITE);logo.startAnimation(brainPulse);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.setPadding(dp(10),0,0,0);TextView title=text("AI CONNECTOR",18,TEXT);title.setTypeface(Typeface.DEFAULT_BOLD);titles.addView(title);TextView sub=text("CORELINK  •  BRIDGE OS",9,BLUE);sub.setTypeface(Typeface.MONOSPACE);titles.addView(sub);header.addView(titles,new LinearLayout.LayoutParams(0,-2,1));LinearLayout status=new LinearLayout(this);status.setOrientation(LinearLayout.VERTICAL);TextView brain=text("◉ AI BRAIN",8,BLUE);brain.setGravity(Gravity.RIGHT);brain.setTypeface(Typeface.MONOSPACE);brain.startAnimation(brainPulse);status.addView(brain);TextView online=text("● ONLINE",9,GREEN);online.setGravity(Gravity.RIGHT);online.setTypeface(Typeface.MONOSPACE);status.addView(online);header.addView(status);root.addView(header);animateIn(header);
        LinearLayout navBar=row();navBar.setPadding(0,0,0,dp(10));navBar.setBackground(bg(Color.rgb(9,17,28),BORDER));pad(navBar,6,6);Button chatNav=button("CHAT",BLUE);navBar.addView(chatNav,new LinearLayout.LayoutParams(0,42,1));Button bridgeNav=button("BRIDGE",Color.rgb(22,64,88));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,42,1);bp.leftMargin=dp(5);navBar.addView(bridgeNav,bp);Button toggle=button("TOOLS",Color.rgb(22,64,88));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,42,1);tp.leftMargin=dp(5);navBar.addView(toggle,tp);Button setup=button("SETUP",Color.rgb(22,64,88));LinearLayout.LayoutParams spn=new LinearLayout.LayoutParams(0,42,1);spn.leftMargin=dp(5);navBar.addView(setup,spn);root.addView(navBar);
        connectorDrawer=new LinearLayout(this);connectorDrawer.setOrientation(LinearLayout.VERTICAL);connectorDrawer.setBackground(bg(CARD,BORDER));connectorDrawer.setVisibility(View.GONE);pad(connectorDrawer,12,8);String[] names={"GitHub","GitLab","Cloudflared","Docker","Vercel","Supabase","Ollama Local","HuggingFace / Meta"};for(String n:names)connectorDrawer.addView(connectorRow(n));root.addView(connectorDrawer,lp(-1,-2));
        LinearLayout bridgeCard=new LinearLayout(this);bridgeCard.setOrientation(LinearLayout.VERTICAL);pad(bridgeCard,12,10);bridgeCard.setBackground(bg(CARD,BORDER));TextView bt=text("BRIDGE CONNECTION",10,BLUE);bt.setTypeface(Typeface.MONOSPACE);bridgeCard.addView(bt);endpoint=new EditText(this);endpoint.setSingleLine(true);endpoint.setText(bridge);endpoint.setTextColor(TEXT);endpoint.setTextSize(12);endpoint.setHintTextColor(MUTED);endpoint.setBackground(bg(Color.rgb(8,15,24),BORDER));endpoint.setPadding(dp(11),0,dp(11),0);LinearLayout.LayoutParams ep=lp(-1,44);ep.topMargin=dp(7);bridgeCard.addView(endpoint,ep);LinearLayout acts=row();acts.setPadding(0,dp(8),0,0);connect=button("CONNECT",BLUE);acts.addView(connect,new LinearLayout.LayoutParams(0,40,1));bridgeStatus=text("Not connected",10,MUTED);bridgeStatus.setGravity(Gravity.CENTER_VERTICAL);bridgeStatus.setPadding(dp(10),0,0,0);acts.addView(bridgeStatus,new LinearLayout.LayoutParams(0,40,1));bridgeCard.addView(acts);LinearLayout navPanel=new LinearLayout(this);navPanel.setOrientation(LinearLayout.VERTICAL);navPanel.setBackground(bg(Color.rgb(9,17,28),BORDER));pad(navPanel,8,4);navPanel.addView(bridgeCard,lp(-1,-2));
        heading(navPanel,"OLLAMA MODEL");modelSpinner=new Spinner(this);modelSpinner.setBackground(bg(Color.rgb(8,15,24),BORDER));modelSpinner.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Connect Bridge to load models"}));navPanel.addView(modelSpinner,lp(-1,44));root.addView(navPanel,lp(-1,-2));
        heading(root,"AI WORKSPACE");chat=text("Bridge belum tersambung.\n\nJalankan Bridge di Termux, lalu tekan CONNECT BRIDGE.",13,MUTED);chat.setGravity(Gravity.TOP);pad(chat,13,13);chat.setBackground(bg(CARD,BORDER));root.addView(chat,lp(-1,500));
        LinearLayout composer=row();composer.setPadding(0,dp(10),0,0);attach=button("+",Color.rgb(22,64,88));composer.addView(attach,lp(46,96));prompt=new EditText(this);prompt.setSingleLine(false);prompt.setGravity(Gravity.TOP);prompt.setMinLines(3);prompt.setHint("Ask Ollama through CORELINK...");prompt.setHintTextColor(MUTED);prompt.setTextColor(TEXT);prompt.setTextSize(12);prompt.setBackground(bg(Color.rgb(8,15,24),BORDER));prompt.setPadding(dp(11),0,dp(11),0);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,96,1);pp.leftMargin=dp(6);composer.addView(prompt,pp);send=button("SEND",BLUE);LinearLayout.LayoutParams sp=lp(82,96);sp.leftMargin=dp(7);composer.addView(send,sp);root.addView(composer);attachmentLabel=text("No attachment",8,MUTED);attachmentLabel.setTypeface(Typeface.MONOSPACE);attachmentLabel.setPadding(0,dp(6),0,0);root.addView(attachmentLabel);TextView foot=text("Bridge 8787  •  Ollama 11434  •  Native Android",8,MUTED);foot.setTypeface(Typeface.MONOSPACE);foot.setPadding(0,dp(10),0,0);root.addView(foot);setContentView(scroll);
        bridgeNav.setOnClickListener(v->{if(navPanel.getVisibility()==View.VISIBLE){navPanel.animate().alpha(0f).translationY(-dp(8)).setDuration(180).withEndAction(()->navPanel.setVisibility(View.GONE)).start();}else{navPanel.setAlpha(0f);navPanel.setTranslationY(-dp(8));navPanel.setVisibility(View.VISIBLE);navPanel.animate().alpha(1f).translationY(0).setDuration(220).start();}});attach.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK_FILE);});toggle.setOnClickListener(v->{if(connectorDrawer.getVisibility()==View.VISIBLE){connectorDrawer.animate().alpha(0f).translationY(-dp(8)).setDuration(180).withEndAction(()->connectorDrawer.setVisibility(View.GONE)).start();}else{connectorDrawer.setAlpha(0f);connectorDrawer.setTranslationY(-dp(8));connectorDrawer.setVisibility(View.VISIBLE);connectorDrawer.animate().alpha(1f).translationY(0).setDuration(220).start();}});chatNav.setOnClickListener(v->scroll.smoothScrollTo(0,0));setup.setOnClickListener(v->showSetup());connect.setOnClickListener(v->connectBridge());send.setOnClickListener(v->sendPrompt());}
    private View connectorRow(String name){LinearLayout r=row();r.setPadding(dp(9),dp(8),dp(9),dp(8));TextView dot=text("●",13,name.equals("Ollama Local")?AMBER:MUTED);r.addView(dot,lp(22,-2));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.addView(text(name,11,TEXT));TextView s=text("Configure after Bridge connects",8,MUTED);s.setTypeface(Typeface.MONOSPACE);c.addView(s);r.addView(c,new LinearLayout.LayoutParams(0,-2,1));r.addView(text("›",20,MUTED));r.setOnClickListener(v->Toast.makeText(this,name+" is configured in Termux .env",Toast.LENGTH_SHORT).show());return r;}
    private void showSetup(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);pad(root,20,22);TextView h=text("BRIDGE SETUP",20,TEXT);h.setTypeface(Typeface.DEFAULT_BOLD);root.addView(h);TextView info=text("Copy this block, paste it into Termux, then run it.",12,MUTED);info.setPadding(0,dp(6),0,dp(14));root.addView(info);TextView box=text(commands,11,Color.rgb(170,215,232));box.setTypeface(Typeface.MONOSPACE);box.setTextIsSelectable(true);box.setBackground(bg(CARD,BORDER));pad(box,12,12);root.addView(box,lp(-1,220));Button copy=button("COPY COMMANDS",BLUE);LinearLayout.LayoutParams cp=lp(-1,46);cp.topMargin=dp(10);root.addView(copy,cp);TextView note=text("After this, run: ollama serve\nThen connect to http://127.0.0.1:8787",11,MUTED);note.setTypeface(Typeface.MONOSPACE);note.setPadding(0,dp(12),0,dp(12));root.addView(note);Button close=button("BACK TO CHAT",Color.rgb(22,64,88));root.addView(close,lp(-1,44));setContentView(root);copy.setOnClickListener(v->copy("CORELINK Termux commands",commands));close.setOnClickListener(v->build());}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==PICK_FILE&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){try{Uri u=data.getData();attachmentName=u.getLastPathSegment()==null?"attachment":u.getLastPathSegment();attachmentMime=getContentResolver().getType(u);if(attachmentMime==null)attachmentMime="application/octet-stream";InputStream in=getContentResolver().openInputStream(u);java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();attachmentBase64=Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP);attachmentLabel.setText("Attached: "+attachmentName+"  (tap + to replace)");}catch(Exception e){Toast.makeText(this,"File gagal dibaca: "+e.getMessage(),Toast.LENGTH_LONG).show();}}}
    private void copy(String label,String value){ClipboardManager cm=(ClipboardManager)getSystemService(Context.CLIPBOARD_SERVICE);cm.setPrimaryClip(ClipData.newPlainText(label,value));Toast.makeText(this,"Copied. Paste in Termux.",Toast.LENGTH_SHORT).show();}
    private void connectBridge(){bridge=endpoint.getText().toString().trim().replaceAll("/$","");bridgeStatus.setText("Connecting...");executor.execute(()->{try{request(bridge+"/health",null);String tags=request(bridge+"/api/ollama/tags",null);ArrayList<String> names=new ArrayList<>();Matcher m=Pattern.compile("\\\"name\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").matcher(tags);while(m.find())names.add(m.group(1));runOnUiThread(()->{bridgeStatus.setText("● Connected");bridgeStatus.setTextColor(GREEN);if(names.isEmpty())names.add("No Ollama model found");modelSpinner.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names));chat.setText("Bridge connected. Ollama siap menerima pesan.");chat.startAnimation(new AlphaAnimation(.35f,1f));});}catch(Exception e){runOnUiThread(()->{bridgeStatus.setText("Connection failed");bridgeStatus.setTextColor(RED);Toast.makeText(this,"Bridge gagal. Jalankan start-termux.sh.",Toast.LENGTH_LONG).show();});}});}
    private void sendPrompt(){String q=prompt.getText().toString().trim();if(q.isEmpty())return;String selected=modelSpinner.getSelectedItem()==null?"qwen2.5-coder:1.5b":modelSpinner.getSelectedItem().toString();chat.setText(chat.getText()+"\n\nYOU\n"+q+"\n\nCORELINK AI\nThinking...");prompt.setText("");executor.execute(()->{try{String attachmentJson=attachmentBase64.isEmpty()?"":" ,\"attachment\":{\"name\":\""+attachmentName.replace("\"","")+"\",\"mime\":\""+attachmentMime+"\",\"base64\":\""+attachmentBase64+"\"}";String body="{\"model\":\""+selected.replace("\"","")+"\",\"prompt\":\""+q.replace("\\","\\\\").replace("\"","\\\"")+"\""+attachmentJson+"}";String response=request(bridge+"/api/agent",body);String answer=response;Matcher o=Pattern.compile("\\\"output\\\"\\s*:\\s*\\\"(.*?)\\\"").matcher(response);if(o.find())answer=o.group(1).replace("\\n","\n"); else if(response.contains("requires_confirmation"))answer="Konfirmasi diperlukan sebelum menjalankan aksi ini: "+response;final String finalAnswer=answer;runOnUiThread(()->{chat.setText(chat.getText()+"\n"+finalAnswer);chat.startAnimation(new AlphaAnimation(.35f,1f));});}catch(Exception e){runOnUiThread(()->chat.setText(chat.getText()+"\nGagal: "+e.getMessage()));}});}
    private String request(String url,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(120000);c.setRequestMethod(body==null?"GET":"POST");c.setRequestProperty("Content-Type","application/json");if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes("UTF-8"));}}int code=c.getResponseCode();BufferedReader r=new BufferedReader(new InputStreamReader(code<400?c.getInputStream():c.getErrorStream()));StringBuilder out=new StringBuilder();String line;while((line=r.readLine())!=null)out.append(line);if(code>=400)throw new Exception("HTTP "+code);return out.toString();}
    @Override protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
}
