plugins {
    id 'com.android.application'
}

android {
    namespace 'com.v1byte.corelink'
    compileSdk 35

    defaultConfig {
        applicationId 'com.v1byte.corelink'
        minSdk 23
        targetSdk 35
        versionCode 16
        versionName '1.7.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        release {
            storeFile file('corelink-release.jks')
            storePassword 'corelink123'
            keyAlias 'corelink'
            keyPassword 'corelink123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
